version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: laravel_php_fpm
    container_name: laravel_php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./storage/app/google/service-account.json:/var/www/html/storage/app/google/service-account.json:ro
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - laravel
    environment:
      DB_HOST: db
      GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON: ${GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON}
      GOOGLE_DRIVE_CREDENTIALS_PATH: ${GOOGLE_DRIVE_CREDENTIALS_PATH}

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: laravel_nginx
    container_name: laravel_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html/public:ro
      - ./storage:/var/www/html/storage:ro
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
    driver: bridge