version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_DATABASE: webprofile_hmif
      DB_USERNAME: root
      DB_PASSWORD: root
      GOOGLE_CREDENTIAL_JSON: ${GOOGLE_CREDENTIAL_JSON} 
      GOOGLE_APPLICATION_CREDENTIALS: /var/www/html/storage/app/google/service-account.json
    depends_on:
      - db
    volumes:
      - .:/var/www/html
      - ./storage/app/google/service-account.json:/var/www/html/storage/app/google/service-account.json
    networks:
      - laravel

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webprofile_hmif
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
    driver: bridge
