version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      target: laravel_php_fpm
    working_dir: /var/www/html
    depends_on:
      - db
    networks:
      - laravel
    environment:
      DB_HOST: db
      GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON: ${GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON}
      GOOGLE_DRIVE_CREDENTIALS_PATH: ${GOOGLE_DRIVE_CREDENTIALS_PATH}
      # Laravel env lainnya
      # APP_KEY: ${APP_KEY}
      # APP_ENV: ${APP_ENV}
      # DB_DATABASE: ${DB_DATABASE}
      # DB_USERNAME: ${DB_USERNAME}
      # DB_PASSWORD: ${DB_PASSWORD}

  web:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
      target: laravel_nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - laravel

  db:
    container_name: mysql
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
    driver: bridge
